### ISSUE TITLE
clamav pod on arm64 fails with 'nc command not found' error

### ISSUE THREAD

**Issue by Anand03** [Cisco-Talos/clamav-docker#28]
clamav pod fails with below error when running on arm64 machine

`Warning  Unhealthy  4s                 kubelet            Readiness probe failed: ERROR: Unable to contact server
/usr/local/bin/clamdcheck.sh: 6: nc: not found`

I had to add `netcat \` installation to `RUN apt update && apt install -y \` in the dockerfile at both stages to fix the issue.

Can you please add it to the main branch. I was not able to create a PR for this.

**Comment by micahsnyder** [comment]
@Anand03 Sure I'd be happy to make a PR and fix it in the `main` branch.

You mention adding `netcat` to be installed for both stages.  I don't think it should be required for the 1st stage though. Is there something I may be missing?

**Comment by Anand03** [comment]
@micahsnyder Thanks for the reply. And yes, inclusion in just the second stage should do the job.
