### ISSUE TITLE
netcat seems to be missing in Debian image to run clamdcheck.sh?

### ISSUE THREAD

**Issue by steffenmueller4** [Cisco-Talos/clamav-docker#30]
Hi all, first of all thank you for providing the clamav-docker images.

I was running `clamav/clamav-debian:latest` image (I guess v1.2), did an docker exec into the running container, and tried to run `./usr/local/bin/clamdcheck.sh`. The output was:

```
./usr/local/bin/clamdcheck.sh: 6: nc: not found
ERROR: Unable to contact server
```

After I have installed netcat via `apt-get install netcat`, it was working:

```
[...]
Setting up netcat (1.10-46) ...
Processing triggers for libc-bin (2.31-13+deb11u6) ...
# ./usr/local/bin/clamdcheck.sh
Clamd is up
```

In the alpine image, clamdcheck.sh works without modification.

Could it be that netcat needs to be installed [here](https://github.com/Cisco-Talos/clamav-docker/blob/main/clamav/1.2/debian/Dockerfile#L109)?

Thank you and BR,
Steffen

**Comment by micahsnyder** [comment]
Hi Steffen

We recently fixed this but haven't updated the images yet: https://github.com/Cisco-Talos/clamav-docker/pull/29

We're still facing some problems with updating databases for every architecture of the clamav-debian image tag and so we haven't really advertised that clamav-debian is ready to go yet.  Sorry it's taking so long!  

Regards,
Micah

**Comment by steffenmueller4** [comment]
Hi Micah,

Awesome, thank you for the update. I am looking forward to getting the fix soon.

Regards,
Steffen

**Comment by micahsnyder** [comment]
We plan to work on solving the clamav-debian update problem starting next week.  We're also prepping to deploy new patch versions for every clamav version so we should have an update to the images mid next week regardless.
