### ISSUE TITLE
Unprivileged entrypoint not included

### ISSUE THREAD

**Issue by robinjhector** [Cisco-Talos/clamav-docker#32]
Hello! I see you have a nice init script that would allow the container to run non-priveleged (as non-root):
https://github.com/Cisco-Talos/clamav-docker/blob/main/clamav/1.2/debian/scripts/docker-entrypoint-unprivileged.sh

However, this file is not included in any built dockerimage... Would it be possible to copy it alongside the regular init script? That would allow me to override `ENTRYPOINT` runtime, and run the container without root.

Or am I missing something obvious here?

**Comment by micahsnyder** [comment]
Tbh, I use docker here and there but didn't know about the `docker --entrypoint PATH` option until now.

That seems like a good solution.  I think we'd discussed building an image that used the unprivileged script by default but your option seems like a lot less work.

**Comment by rsundriyal** [comment]
Created a PR to fix it. 

@robinjhector Thanks for feedback. Always appreciated.
