### ISSUE TITLE
clamav-debian:stable only has tags for amd64

### ISSUE THREAD

**Issue by Newspaperman57** [Cisco-Talos/clamav-docker#35]
Hi, first of all, thank you for making multi-arch images. A lot of our infrastructure is based on power and it can be a pain sometimes, but it's very helpful when corporations distribute multi-arch images, but i've noticed a slight inconvenience:

Only the most specific version-tags of the debian-based container actually contain ppc64le and arm64 compatible images. For example, `clamav-debian:1.2.0-6` contains these tags according to docker-hub:

![image](https://github.com/Cisco-Talos/clamav-docker/assets/1321620/a3c94611-85f2-4939-8428-cdb6cacd017a)

But the `stable` and `latest` tags do not:

![image](https://github.com/Cisco-Talos/clamav-docker/assets/1321620/e8b9b62a-1a34-4277-b1fe-4f839316674d)

**Comment by micahsnyder** [comment]
Hi @Newspaperman57 sorry for the delayed response. I am unsure why the `latest` and `stable` tags do not match `1.2.0-6`.  I went and looked at  https://hub.docker.com/r/clamav/clamav-debian/tags and see that the `1.2.0` and `1.2` tags also don't match `1.2.0-6`. 

The clamav-debian images are still somewhat a work in progress.  My team is actively working on it with this PR https://github.com/Cisco-Talos/clamav-docker/pull/33

I'm hopeful this will be fixed within a week or so.

**Comment by micahsnyder** [comment]
This was fixed. Sorry I forgot to update the ticket.  The images are now ready to use.

**Comment by mvysny** [comment]
I am unable to find `linux/arm64` arch at https://hub.docker.com/r/clamav/clamav/tags - only linux/amd64 is available. Have those images been pulled down perhaps?
