### ISSUE TITLE
Release Image for ClamAV 1.3.0-rc to Docker Hub

### ISSUE THREAD

**Issue by candrews** [Cisco-Talos/clamav-docker#37]
Can you please release an image to Docker Hub for the [1.3.0-rc](https://github.com/Cisco-Talos/clamav/releases/tag/clamav-1.3.0-rc) version?

The current latest version there is 1.2.1: https://hub.docker.com/r/clamav/clamav/tags

Thank you!

**Comment by micahsnyder** [comment]
In the past we haven't done docker tags for release candidates and have asked users to test the RC using the clamav/clamav:unstable and clamav:clamav:unstable_base tags.  The release candidates aren't intended for production use.
