### ISSUE TITLE
Debian and Alpine built with the same tags

### ISSUE THREAD

**Issue by avishefi** [Cisco-Talos/clamav-docker#5]
The Jenkinsfiles look the same, and there are no different tags on Docker Hub for either Alpine or Debian.

**Comment by barborico** [comment]
+1
The Jenkinsfiles for debian specifically pull the alpine Dockerfiles and scripts; see e.g. https://github.com/Cisco-Talos/clamav-docker/blob/fdc41e9d0a3833e39e0c4a2fb3d56da0c01ebdb2/clamav/1.0/debian/Jenkinsfile#L50.

**Comment by avishefi** [comment]
@micahsnyder I see #11 is merged, can't we use it to create additional tags on `clamav/clamav`?

**Comment by micahsnyder** [comment]
> @micahsnyder I see #11 is merged, can't we use it to create additional tags on `clamav/clamav`?

We don't publish debian-based images to `clamav/clamav` yet, so that wouldn't make any sense.  We ought to start publishing them to `clamav/clamav-debian` as I mentioned yesterday.  With the fix you made I think it may be good to go. .

**Comment by rsundriyal** [comment]
As per the last merge #33, we now publish separate image tags for the Alpine and Debian images. 

Please go through the [README.md](https://github.com/Cisco-Talos/clamav-docker/blob/main/README.md) for more details about images/repos/tags.

As the issue is now obsolete, I am closing the issue.
