### ISSUE TITLE
Support for more than linux/amd64

### ISSUE THREAD

**Issue by koehn** [Cisco-Talos/clamav-docker#59]
Any chance you’d post official images supporting other platforms? I use linux/arm64 in addition to linux/amd64. On most machines it's as simple as `docker buildx build --platform linux/amd64,linux/arm64 -t clamav/clamav:$VERSION --push .`

**Comment by micahsnyder** [comment]
We have Debian-based images for arm64, amd64, and ppc64le under the name "clamav-debian": https://hub.docker.com/r/clamav/clamav-debian/tags

We do not plan to build alpine image for other architectures.
