### ISSUE TITLE
Default unix socket path to which clamd binds to has changed in v1.0

### ISSUE THREAD

**Issue by Kami** [Cisco-Talos/clamav-docker#6]
It appears that with the ``1.0`` Docker image, local unix socket path to which ``clamd`` binds to has changed.

It used to be ``/var/run/clamd.sock`` and with v1.0 it is ``/tmp/clamd.sock``.

I'm not sure if that change was intentional or not, but all the docs, etc. still claim ``{/var}/run/clamav/clamd.sock`` as the socket path inside the Docker container (https://github.com/Cisco-Talos/clamav/blob/main/README.Docker.md).

The fix / solution is simple (changing ``LocalSocket /tmp/clamd.sock`` config option in ``/etc/clamav/clamd.conf``), but I haven't created a PR with that change yet. I first want to understand if this change was intentional in v1.0 or not (or in case I'm doing anything wrong - although I haven't changed anything beyond upgrading from ``clamav/clamav:0.104.4`` docker tag to ``clamav/clamav:1.0.0``). And in case it was indeed intentional, docs likely need to be updated.

I'm using default Docker image (``clamav/clamav:1.0.0``) as-is without any changes.

``clamconf -n``  output from inside the container

```bash
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
LogFile = "/var/log/clamav/clamd.log"
LogTime = "yes"
PidFile = "/tmp/clamd.pid"
LocalSocket = "/tmp/clamd.sock"
TCPSocket = "3310"
User = "clamav"

Config file: freshclam.conf
---------------------------
PidFile = "/tmp/freshclam.pid"
UpdateLogFile = "/var/log/clamav/freshclam.log"
DatabaseMirror = "database.clamav.net"

Config file: clamav-milter.conf
-------------------------------
LogFile = "/var/log/clamav/milter.log"
LogTime = "yes"
PidFile = "/tmp/clamav-milter.pid"
User = "clamav"
ClamdSocket = "unix:/tmp/clamd.sock", "unix:/tmp/clamd.sock", "unix:/tmp/clamd.sock", "unix:/tmp/clamd.sock", "unix:/tmp/clamd.sock"
MilterSocket = "inet:7357"

Software settings
-----------------
Version: 1.0.0
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /var/lib/clamav
daily.cld: version 26738, sigs: 2013306, built on Fri Dec  2 11:12:06 2022
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 12:32:42 2021
bytecode.cvd: version 333, sigs: 92, built on Mon Mar  8 15:21:51 2021
Total number of signatures: 8660825

Platform information
--------------------
uname: Linux 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64
OS: Linux, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.13 (1.2.13), compile flags: a9
platform id: 0x0a21a0a008000000000b0201

Build information
-----------------
GNU C: 11.2.1 20220219 (11.2.1)
sizeof(void*) = 8
Engine flevel: 160, dconf: 160
```

**Comment by Kami** [comment]
I wonder if it's related to this change (https://github.com/Cisco-Talos/clamav-docker/commit/a1cd0b0d0251e2c72781aebf2ae728a3c7f2e8df), or similar.

It appears that change was only added to ``0.104.x`` tag and not 1.0.0 (https://github.com/Cisco-Talos/clamav-docker/pull/4/files).

**Comment by micahsnyder** [comment]
Sorry about the delay responding to this.  It's a new repository and I personally forgot to follow all activity on it and didn't get notifications about the new issues. 

The change to use `/tmp/clamd.sock` instead of `/var/run/clamd.sock` was an intentional step towards being able to build an unprivileged/rootless image as requested by https://github.com/Cisco-Talos/clamav/issues/478

It looks like we forgot to update the documentation to note the change in the clamd.sock location.

**Comment by micahsnyder** [comment]
I just updated the docs:
- https://github.com/Cisco-Talos/clamav-docker/commit/dd5920eae0779d519e2252b793d732d521177d7a
- https://github.com/Cisco-Talos/clamav-documentation/commit/dcb070ae1c0ed4260a06ce8982b8feed4a07ef79
