### ISSUE TITLE
Newer Docker Images are eight times larger and perform way worse

### ISSUE THREAD

**Issue by hebelal** [Cisco-Talos/clamav-docker#7]
Hi,

We use the clamav docker image in version [0.105.1_base](https://hub.docker.com/layers/clamav/clamav/0.105.1_base/images/sha256-eb010c5c4e50e86c25b80c9a82655a0ccdebfa163e55076ff1cba05183258f7a?context=explore).
Recently we noticed that the performance of our scans got way worse (takes twice as long) with one of the latest updates.
We also noticed that the docker image size increased from 11,76MB to 72,92MB with 0.105.1-3_base to 0.105.1-4_base.
Could it be that the slow performance and big image size are connected to each other (maybe the debug build mistakenly got shipped) ?

Best regards,
Alex

**Comment by micahsnyder** [comment]
@hebelal the `0.105.1-4` images are built differently than `0.105.1-3`.  The explanation is a little difficult, but in short we did it to patch some bugs as quickly as possible. I think we can revert to the old way of building them now that alpine 3.17 is out, which would probably get things back to how they used to be.

**Comment by harsh-saini-E2842** [comment]
@micahsnyder I am facing the same issue with the 1.0 version, is it expected in the 1.0 version also?

Also, when are you planning to revert it back?

**Comment by micahsnyder** [comment]
Just merged the PR that should restore the performance back to the was it was in the 0.105.1-1 image. We will push updated images for 0.105.1, 1.0.0, and unstable shortly.
