### ISSUE TITLE
Publish ARM images

### ISSUE THREAD

**Issue by tenjaa** [Cisco-Talos/clamav-docker#8]
Hi,
do you plan on publish ARM builds of the images?
Currently I can only see linux/amd64.

**Comment by DerLinkman** [comment]
+1 (for ARM64) from the mailcow: dockerized project. 

Would skip the step of building the image by ourself which is technically not nessesary if you publish clamav for ARM64 as well.

**Comment by polarathene** [comment]
> +1 (for ARM64) from the mailcow dockerized project.

Not sure if it'd work for mailcow, haven't looked at how that is managed there. But `docker-mailserver` just installs a clamav package and [uses `COPY --link --chown` to get the latest database updates](https://github.com/docker-mailserver/docker-mailserver/blob/423188176f065f0a5f50972d9aa10d3e2b869e1b/Dockerfile#L33-L50) from the official clamav image.

- `--link` excludes it from our published image weight, that data is added as part of `docker pull` on the users machine, sourcing it from the ClamAV image at pull time.
- `--chown` ensures file permissions are maintained IIRC, so it's not chaned to `root`. There is a gotcha however that prevented us from using `--chown=clamav`, so in our build script that installs the package, we also create a `clamav` user in advance with a high enough UID/GID (_so it doesn't change dynamically in image updates when packages are added/removed that create other users or groups_) and set that ID value for `--chown` which works.

I have a [comment here](https://github.com/Cisco-Talos/clamav-docker/pull/11#issuecomment-1383605117) in this repo documenting details about that if it's of interest :)

---

For building and publishing ARM images, perhaps the project here could adopt Github Actions? It makes this very simple to support and maintain. `docker-mailserver` does this and I helped work on those actions (_[here's our re-usable publish](https://github.com/docker-mailserver/docker-mailserver/blob/423188176f065f0a5f50972d9aa10d3e2b869e1b/.github/workflows/generic_publish.yml) job that other workflows call_).

**Comment by rsundriyal** [comment]
Closing the issue as arm64 images are available under clamav/clamav-debian [repository](https://hub.docker.com/r/clamav/clamav-debian/tags).

**Comment by szaimen** [comment]
Can we please open this again? I need alpine based multiarch images. Or shall I open a new issue?
